"""0004 add user model

Revision ID: f89735288527
Revises: d9388daaf807
Create Date: 2025-11-12 17:35:15.025360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89735288527'
down_revision = 'd9388daaf807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_username'))

    op.drop_table('user_model')
    # ### end Alembic commands ###
